### ISSUE TITLE
No muestra imagen payment-methods.png

### ISSUE THREAD

**Issue by alexavalossv** [lastcron/binario-wompi-gateway-transparente#1]
¡Hola! Saludos cordiales y muchas gracias por compartir el fork. Me será de mucha utilidad. 
Soy nuevo en github y no se si esto lo tengo que decir aquí jejeje... Sino es aquí me perdonan. 

He instalado el fork, y en el checkout no se muestra la imagen payment-methods.png he ido a ver a binario-wompi-gateway-transparente/assets/images/payment-methods.png y la imagen esta en su sitio y funciona correctamente.

**Comment by lastcron** [comment]
Gracias Alex , ya vimos el inconveniente. La ruta que le pusimos a la imagen esta mala. Intentarenos corregirlo ahora .

Saludos

**Comment by lastcron** [comment]
Archivo wc-binario-wompi-payment.php -> Linea 11 , solo comentala y eliminas por completo la imagen. Te aviso cuando este corregida.

**Comment by lastcron** [comment]
Ya pueden descargar nuevamente el paquete. El problema de la imagen ya esta corregido. Gracias por los comments.
